from __future__ import annotations

import json
from io import BytesIO
from typing import Any
from zipfile import ZIP_DEFLATED, ZipFile

import pandas as pd


def build_run_summary(
    run_row: pd.Series,
    events_df: pd.DataFrame,
    failures_df: pd.DataFrame,
    policy_assessment: dict[str, Any] | None = None,
) -> dict:
    severity_counts = events_df["severity"].value_counts().to_dict() if not events_df.empty else {}
    event_counts = events_df["event_type"].value_counts().to_dict() if not events_df.empty else {}

    return {
        "run": {
            "id": int(run_row["id"]),
            "name": run_row["name"],
            "source_file": run_row["source_file"],
            "started_at": run_row["started_at"],
            "ended_at": run_row["ended_at"],
            "total_rows": int(run_row["total_rows"]),
            "created_at": run_row["created_at"],
        },
        "event_summary": {
            "total_events": int(len(events_df)),
            "by_type": event_counts,
            "by_severity": severity_counts,
        },
        "failure_summary": {
            "total_failures": int(len(failures_df)),
            "open_failures": int((failures_df["status"] == "open").sum()) if not failures_df.empty else 0,
            "resolved_failures": int((failures_df["status"] == "resolved").sum()) if not failures_df.empty else 0,
        },
        "policy_assessment": policy_assessment,
    }


def export_bundle(summary: dict, events_df: pd.DataFrame, failures_df: pd.DataFrame) -> bytes:
    json_payload = json.dumps(summary, indent=2)
    markdown_payload = summary_to_markdown(summary)

    events_csv = events_df.to_csv(index=False) if not events_df.empty else ""
    failures_csv = failures_df.to_csv(index=False) if not failures_df.empty else ""

    memory_zip = BytesIO()
    with ZipFile(memory_zip, mode="w", compression=ZIP_DEFLATED) as zf:
        zf.writestr("summary.json", json_payload)
        zf.writestr("summary.md", markdown_payload)
        zf.writestr("events.csv", events_csv)
        zf.writestr("failures.csv", failures_csv)

    memory_zip.seek(0)
    return memory_zip.read()


def summary_to_markdown(summary: dict) -> str:
    run = summary["run"]
    event_summary = summary["event_summary"]
    failure_summary = summary["failure_summary"]
    policy_assessment = summary.get("policy_assessment")

    lines = [
        "# Autonomous Test Run Report",
        "",
        "## Run Info",
        f"- Run ID: {run['id']}",
        f"- Name: {run['name']}",
        f"- Source File: {run['source_file']}",
        f"- Created At: {run['created_at']}",
        f"- Start: {run['started_at']}",
        f"- End: {run['ended_at']}",
        f"- Samples: {run['total_rows']}",
        "",
        "## Event Summary",
        f"- Total Events: {event_summary['total_events']}",
        "- By Type:",
    ]

    if event_summary["by_type"]:
        for key, value in event_summary["by_type"].items():
            lines.append(f"  - {key}: {value}")
    else:
        lines.append("  - None")

    lines.extend(["", "- By Severity:"])
    if event_summary["by_severity"]:
        for key, value in event_summary["by_severity"].items():
            lines.append(f"  - {key}: {value}")
    else:
        lines.append("  - None")

    lines.extend(
        [
            "",
            "## Failure Summary",
            f"- Total Failures: {failure_summary['total_failures']}",
            f"- Open Failures: {failure_summary['open_failures']}",
            f"- Resolved Failures: {failure_summary['resolved_failures']}",
        ]
    )

    if policy_assessment:
        lines.extend(
            [
                "",
                "## Policy Verdict",
                f"- Verdict: {policy_assessment.get('verdict', 'unknown')}",
            ]
        )
        if policy_assessment.get("version") is not None:
            lines.append(f"- Snapshot Version: {policy_assessment.get('version')}")
        if policy_assessment.get("evaluated_at"):
            lines.append(f"- Evaluated At: {policy_assessment.get('evaluated_at')}")
        rule_rows = policy_assessment.get("rules", [])
        if rule_rows:
            lines.append("- Rules:")
            for rule in rule_rows:
                status = "PASS" if rule.get("passed") else "FAIL"
                lines.append(
                    "  - "
                    f"{rule.get('rule_id')} [{status}] "
                    f"observed={rule.get('observed')} limit={rule.get('max_allowed')}"
                )

    lines.extend(["", "Generated by Autonomy Test Logger."])

    return "\n".join(lines)
